name: Gerar Build do Site

on:
  workflow_dispatch: # Isso cria um botão para você gerar o site quando quiser

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm install
      - run: npm run build
      - name: Disponibilizar para download
        uses: actions/upload-artifact@v4
        with:
          name: site-pronto-dist
          path: dist/
