name: Deploy para HostGator

on:
  workflow_dispatch: # Permite que você rode manualmente se quiser
  push:
    branches:
      - main # Toda vez que você salvar algo na branch principal, ele atualiza

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Baixar o código do GitHub
        uses: actions/checkout@v3

      - name: Instalar dependências e Gerar o Site (Build)
        run: |
          npm install
          npm run build

      - name: Preparar arquivos ocultos para envio
        run: |
          mkdir -p hostgator-deploy
          cp -a dist/. hostgator-deploy/

      - name: Enviar arquivos para HostGator via SSH
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          passphrase: ${{ secrets.SSH_PASSPHRASE }}
          port: 2222 # Porta padrão da HostGator para SSH
          source: "hostgator-deploy/*,hostgator-deploy/.htaccess" # Inclui arquivos ocultos como .htaccess
          target: "public_html/" # Pasta do seu site na HostGator
          strip_components: 1 # Para não criar uma pasta 'hostgator-deploy' dentro do site
